language: node_js
node_js:
    - "9.2.1"
script: 
    - npm run travis
    - ng test --single-run

before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install


